#!/usr/bin/env python3

#--- Improve Demo Notebook Onboarding & Offboarding----------------------------#
###nbformat use to drop the first few notebook cells, based on https://stackoverflow.com/a/71244733/8508004 to get fourth cell forward.
# Don't want first cell because first cell currently, which is at https://github.com/febos/SQUARNA/blob/main/demo.ipynb , has install and don't need and some weird empty cell. Plus should have a header so might as well add that and add import back at that time to make separating out content at this stage easier.
cell_to_start_collecting_at = 4 # number of cell to start the span of cells to collect; first cell gets number 1 in bracket if run so use that numbering
length_of_cell_block_to_keep = 15 # length of sequential span of cells to keep; HERE want to drop the blank cells at the end
import nbformat as nbf
ntbk = nbf.read("demo.ipynb", nbf.NO_CONVERT)
new_ntbk = ntbk
new_ntbk.cells = [cell for indx, cell in enumerate(ntbk.cells) if cell_to_start_collecting_at - 2 < indx < (cell_to_start_collecting_at + length_of_cell_block_to_keep - 1)]
nbf.write(new_ntbk, "demo.ipynb", version=nbf.NO_CONVERT)
###END OF nbformat use to drop the first notebook cell.


### add a header and `import SQUARNA` as first code cell in demo nb (somewhat adpated from https://github.com/jupyter/nbformat/issues/176#issuecomment-610214638)
header_md_text_to_add = """\
# SQUARNA demo
Run all the cells using the menu option '`Run`' > '`Run All`'.\n
Alternatively, to execute code in a single cell, select the cell and press Shift + Enter. This allows you to run the cells sequentially one by one, stepping through the notebook's execution.

-------------
"""

code_to_add = """\
import SQUARNA"""

footer_md_text_to_add = """\
-------------

Enjoy!
"""

ntbk = nbf.read("demo.ipynb", nbf.NO_CONVERT)
modified_ntbk = ntbk
modified_header_cells_listing = [nbf.v4.new_markdown_cell(header_md_text_to_add), nbf.v4.new_code_cell(code_to_add)]
footer_cells_listing = [nbf.v4.new_markdown_cell(footer_md_text_to_add)]
modified_ntbk.cells = modified_header_cells_listing + ntbk.cells + footer_cells_listing 
nbf.write(modified_ntbk, "demo.ipynb", version=nbf.NO_CONVERT)
###END OF nbformat use to add header and import.
#--- END of Improving Demo Notebook On & off boarding--------------------------#